# Generated by Django 2.0.6 on 2018-07-03 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pewad', '0005_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecord',
            name='cont',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pewad.Contract', verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pewad.Employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='workrecord',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pewad.Project', verbose_name='Project'),
        ),
    ]
