# Generated by Django 2.0.6 on 2018-06-21 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Contract Name')),
                ('number', models.IntegerField(verbose_name='Contract Number')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Project Name')),
                ('abbr', models.CharField(max_length=100, verbose_name='Abbr.')),
                ('desc', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='WorkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(max_length=4, verbose_name='Hours')),
                ('workTasking', models.TextField(verbose_name='Assignment')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employd.Contract')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employd.Employee')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='employd.Employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employd.Project')),
            ],
        ),
    ]
