# Generated by Django 2.0.6 on 2018-06-22 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EMPLOYD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workrecord',
            name='lead',
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EMPLOYD.Employee', verbose_name='Lead'),
        ),
    ]
