# Generated by Django 2.1.1 on 2018-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employd', '0006_auto_20180703_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='jmadrox@gblsys.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
